config/routes.rb
Rails.application.routes.draw do
 
  get 'reminders/oilchange'
  resources :reminders
  get 'notifications/reminder'
  #devise_for :users
  
  get 'welcome/home', to: 'welcome#home'
  #root to: 'welcome#home'
  
  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign me up' }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :maintenance_actions
  
  resources :users
  resources :vehicles do
  resources :maintenance_actions 
  end


  get "maintenance_actions/reminder", to: "maintenance_actions#reminder"
  resources :vehicles do
    get 'reminders/oilchange'
    resources :receipts
    resources :maintenance_logs do
      
      resources :maintenance_actions 
    end
      
  end
     


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end

app/models/alignment.rb
class Alignment < MaintenanceAction

end  
  

app/models/antifreeze.rb
class Antifreeze < MaintenanceAction

end  
  

app/models/brake.rb
class Brake < MaintenanceAction

end
  

app/models/brake_fluid.rb
class BrakeFluid < MaintenanceAction
 
end  

app/models/converted_receipt.rb
class ConvertedReceipt < ApplicationRecord
    belongs_to :maintenance_log
    
    def search(string)
       content_text = self.content.downcase
       if content_text[string]
        return true
       else
        return false
       end
    end
end

app/models/generate_pdf.rb
class GeneratePdf < Prawn::Document

  include ActionView::Helpers::NumberHelper

  def initialize (maintenance_action)
    super(top_margin: 20)
    @maintenance_actions = maintenance_action.order("service_date")
    line_items
    
    end
  end


  def line_items
    move_down 50
    table line_item_rows do
      row(0).font_style = :bold
      columns(1..3).align = :right
      self.row_colors = ['DDDDDD', 'FFFFFF']
      self.header = true
    end
  end


  def line_item_rows
  
    [["Maintnenace Type", "Service Date", "Mileage", "Cost" ]] +
      @maintenance_actions.map do |maintenance_action|
      [maintenance_action.type, maintenance_action.service_date, maintenance_action.mileage, number_to_currency(maintenance_action.cost)]
      
    end
  end
  

  private

  def generate_pdf
    params.permit(:vehicle_id, :maintenance_log_id, :maintenance_action_id )
  end

  def maintenance_action_params
    params.require(:maintenance_action).permit(:id, :maintenance_log_id, :type, :mileage, :oil_type, :service_date, :cost, :tire_location, :brake_location, :rotor_location, :notes, :selected)
  end
  
  def maintenance_log_params
    params.require(:maintenance_log).permit(:id)
  end
  def vehicle_params
    params.require(:vehicle).permit(:id, :name, :year, :make, :model, :insurance, :vin, :license_plate,
                                    :tire_psi, :registration, :title, :inspection, :color, :user_id, 
                                    :authenticity_token)
 end

  

app/models/maintenance_log.rb
class MaintenanceLog < ApplicationRecord
  
  has_many :maintenance_actions
  belongs_to :vehicle, dependent: :destroy
  accepts_nested_attributes_for :maintenance_actions
  has_one_attached :image
  has_one :converted_receipt
end

app/models/miscellaneous.rb
class Miscellaneous < MaintenanceAction

end  

app/models/oil_change.rb
class OilChange < MaintenanceAction
  

end

app/models/reminder.rb
class Reminder < ApplicationRecord
end

app/models/rotor.rb
class Rotor < MaintenanceAction
end
  

app/models/tire_replacement.rb
class TireReplacement < MaintenanceAction
end  

app/models/tire_rotation.rb
class TireRotation < MaintenanceAction

end

app/models/transmisson_fluid.rb
class TransmissionFluid < MaintenanceAction
     
end   

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :trackable, :validatable

  has_many :vehicles, dependent: :destroy
  has_one_attached :avatar
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

  belongs_to :user
  has_many :maintenance_logs
  has_one_attached :avatar
  #has_one_attached :registration
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  
  require "prawn"
    
  
  def index
    @vehicles = current_user.vehicles
    # redirect_to new_vehicle_path
  end


  def show
    @vehicle = Vehicle.find(params[:id])
  end
 

  def new
    @vehicle = Vehicle.new
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
    # unless current_user.id == @vehicle.user_id
    #   redirect_to vehicles_path 
    # end
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user_id = current_user.id
  
  
    
    if @vehicle.save
      
      redirect_to vehicles_path
    else
      render 'new'
    end
    
  end  
  
  def update
    @vehicle = Vehicle.find(params[:id])

    if @vehicle.update(vehicle_params)
        redirect_to vehicles_path
    else
        render 'edit'
    end
  end

  def destroy 
    @vehicle = Vehicle.find(params[:id])
      @vehicle.destroy
      redirect_to vehicles_path
  end
 
  

  private

    def vehicle_params
       params.require(:vehicle).permit(:name, :year, :make, :model, :insurance, :vin, :license_plate,
                                       :tire_psi, :registration, :title, :inspection_date, :color, :user_id, 
                                       :authenticity_token, :avatar)
    end

    # def set_vehicle
    #   @vehicles = current_user.vehicles
    # end

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle, local: true) do |f| %>
    <ons-list modifier="inset">
      <ons-list-header>Vehicle Information</ons-list-header>
      <ons-list-item modifier="longdivider"><%= f.text_field :name, autocomplete: "name", class: 'text-input', placeholder: 'Vehicle Nickname' %></ons-list-item>
      <ons-list-item modifier="longdivider"><%= f.text_field :color, autocomplete: "color", class: 'text-input', placeholder: 'Color' %></ons-list-item>
    </ons-list>
    <br>
    <ons-list modifier="inset">
      <ons-list-item modifier="longdivider"><%= f.text_field :make, autocomplete: "make", class: 'text-input', placeholder: 'Make' %></ons-list-item>
      <ons-list-item modifier="longdivider"><%= f.text_field :model, autocomplete: "model", class: 'text-input', placeholder: 'Model' %></ons-list-item>
      <ons-list-item modifier="longdivider"><%= f.text_field :year, autocomplete: "year", class: 'text-input', placeholder: 'Year' %></ons-list-item>
    </ons-list>
    <br>
    <ons-list modifier="inset">
      <ons-list-item modifier="longdivider"><i class="far fa-question-circle" style= font-size:0.8rem;
            onclick="ons.notification.toast('The VIN (vehicle identification number) can often be found on the lower-left corner of the dashboard, in front of the steering wheel. You can read the number by looking through the windshield.', { timeout: 3000})">
            </i><%= @vehicle.vin %><%= f.text_field :vin, autocomplete: "vin", class: 'text-input', placeholder: '  VIN#' %></ons-list-item>
      <ons-list-item modifier="longdivider"><%= f.text_field :license_plate, autocomplete: "license_plate", class: 'text-input', placeholder: 'License Plate #' %></ons-list-item>
      <ons-list-item modifier="longdivider" style="color:grey;">Date of Last Inspection: <%= f.date_field :inspection_date, autocomplete: "inspection_date", class: 'text-input', placeholder: 'Date of last Inspection' %></ons-list-item>
    </ons-list>
    <div style="display:block; text-align: center; margin-top: 10px;">
        <p id="upload_msg" >Upload a picture of your vehicle</p>
        <i id="check_mark" class="fa fa-check-circle" style="font-size:36px;color:blue"></i>  
        <i class="fa fa-camera button" id="camera_button" style="margin:15px; background-color: white; color:#3A405A; "></i>
   </div>
    <%= f.file_field :avatar, multiple: false,
                  direct_upload: true, accept:"image/*", capture:"camera", style:"margin:10px; font-size: 1.2rem;"%>
    <div class="actions" style="text-align: center; margin-top: 30px; margin-bottom: 30px;">
      <%= f.submit "Submit", class: "button", style:"background-color: white; color:#3A405A; font-weight: bold;" %>
    </div>
<% end %> 
<style>
#vehicle_avatar{
  display:none;
}
#check_mark{
  display: none;
}
</style>
<script>
  var camera_button = document.getElementById("camera_button")
    camera_button.addEventListener('click',function(e){
        var vehicle_image_upload = document.getElementById("vehicle_avatar")
        vehicle_image_upload.click();

       
    })

     
    var vehicle_image_input= document.getElementById("vehicle_avatar")
    vehicle_image_input.addEventListener('change', function(e){
        if (vehicle_image_input.files.length >0){
          var check_mark = document.getElementById("check_mark").style.display="block"
          var upload_msg = document.getElementById("upload_msg").style.display ="none"
        }
    })
</script>

app/views/vehicles/edit.html.erb
<ons-page>
  <ons-toolbar style="background-color: #3A405A;">
    <div class="left">
       <ons-toolbar-button><%= link_to 'Back', :back, class: "button--quiet", style:"color:white;" %></ons-toolbar-button>
    </div>
    <div class="center" style="color:white;"><ons-toolbar-button><%= link_to 'GloveBox', vehicles_path, class:"button--quiet", style:"color: white; font-weight:bold;" %></ons-toolbar-button></div>
  </ons-toolbar>
 
<h2 style="text-align: center; margin-top: 10px; font-family: 'Raleway', sans-serif;">Edit Vehicle</h2>


<%= render 'form' %>

app/views/vehicles/index.html.erb
<style>

.sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #3A405A;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
}

.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: white;
    display: block;
    transition: 0.3s;
}

.sidenav a:hover {
    color: #f1f1f1;
}

.sidenav .closebtn {
    position: absolute;
    top: 30px;
    right: 5px;
    font-size: 36px;
    margin-left: 50px;a
    
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>

<ons-page>

  <ons-toolbar style="width: 100%; background-color: #3A405A;">
    <div class="toolbar__left" style="width: 33%;" >
      <ons-toolbar-button><%= link_to 'GloveBox', vehicles_path, class:"button--quiet", style:"color: white; font-weight: bold;" %></ons-toolbar-button>
    </div>
    
    <div class="toolbar__right" style="width: 33%;" >
      <p onclick="openNav()" class="button--quiet" style="color: white;">Menu</p>
      

    </div>
  </ons-toolbar>
  <div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to('Account', user_path(current_user.id, style:"color: white;")) %>
  <%= link_to 'Add a Vehicle', new_vehicle_path%>
  <a href="tel:+1-800-222-4357" style="color: white;">Call AAA</a>
  <%= link_to('Sign Out', destroy_user_session_path, method: :delete) %>
  
</div>

<% if notice %>
<p class="alert alert-primary"><%= notice %></p>
<% end %>
 
<h2 style="text-align: center; margin-top: 10px; font-family: 'Raleway', sans-serif; font-weight: bold;"><%="#{current_user.first_name}'s GloveBox"%></h2>

<%@vehicles.each do |vehicle| %>

  
    <ons-card class=" card card--material" style="max-width: 100% ">
    <%= link_to vehicle_path(vehicle) do %>
        <%if vehicle.avatar.attached?%>
          <%= image_tag(vehicle.avatar.service_url, width:"100%",id:"vehicle-img")%>
        <%else%>
          <%= image_tag("https://s3.amazonaws.com/gloveboxassets/vehicle_default2.jpeg", width:"100%",id:"vehicle-img")%>
        <%end%>
    <%end%>
    <div class="title">
      <%= link_to vehicle.name.split.map(&:capitalize).join(' '), vehicle_path(vehicle),  class:"button--quiet", style:"color: #3A405A;" %>
    </div>
    <div class="content">
      <ons-list>
        
        <ons-row>
          <ons-col width="25%" style="font-family: 'Raleway', sans-serif;"><%= vehicle.year %></ons-col>
          <ons-col width="25%" style="font-family: 'Raleway', sans-serif;"><%= vehicle.make %></ons-col>
          <ons-col width="25%" style="font-family: 'Raleway', sans-serif;"><%= vehicle.model %></ons-col>
          <ons-col width="25%" style="font-family: 'Raleway', sans-serif;"><%= vehicle.license_plate %></ons-col>

        </ons-row>
      </ons-list>
    </div>
  </ons-card>

<%end%>



<div id="form--new" style="margin-top: 50px;"></div>
<div class="actions" style="text-align: center; margin-top: 30px; margin-bottom: 30px;">
  <%= link_to 'Add a Vehicle', new_vehicle_path, class: "button", style:"background-color: white; color:#3A405A; font-weight: bold;"%>
</div>


</ons-page>

app/views/vehicles/new.html.erb
<ons-page>
  <ons-toolbar style="background-color: #3A405A;">
    <div class="left">
      <ons-toolbar-button><%= link_to 'Back', :back, class: "button--quiet", style:"color:white;" %></ons-toolbar-button>
    </div>
    <div class="center" style="color:white;"><ons-toolbar-button><%= link_to 'GloveBox', vehicles_path, class:"button--quiet", style:"color: white; font-weight:bold;" %></ons-toolbar-button></div>
  </ons-toolbar>
 
<h2 style="text-align: center; margin-top: 10px; font-family: 'Raleway', sans-serif;">Add a Vehicle</h2>


<%= render 'form' %>

app/views/vehicles/show.html.erb
<ons-page>

 <%= render "shared_header/header"%>


<% if notice %>
<p class="alert alert-primary"><%= notice %></p>
<% end %>

<h2 style="text-align: center; margin-top: 10px; font-family: 'Raleway', sans-serif; font-weight: bold;"><%="#{@vehicle.name.split.map(&:capitalize).join(' ')}"%></h2>


<ons-card style="max-width: 100%">
        <%if @vehicle.avatar.attached?%>
          <%= image_tag(@vehicle.avatar.service_url, width:"100%",id:"vehicle-img")%>
        <%else%>
          <%= image_tag("https://s3.amazonaws.com/gloveboxassets/vehicle_default2.jpeg", width:"100%",id:"vehicle-img")%>
        <%end%>
    <div class="title">

      <%= link_to @vehicle.name.split.map(&:capitalize).join(' '), vehicle_path(@vehicle),  class:"button--quiet", style:"font-weight: bold; font-size: 1.5rem; color: #3A405A;" %>
    </div>
    <div class="content">
      <ons-list>
        <ons-row style=" margin-bottom: 15px;">
          <ons-col width="100%" style="font-size:1.2rem; font-family: 'Raleway', sans-serif;"><strong>Year:  </strong><%= @vehicle.year %></ons-col>
        </ons-row>
      </ons-list>
      <ons-list>
        <ons-row style=" margin-bottom: 15px;">
          <ons-col width="100%" style="font-size:1.2rem; font-family: 'Raleway', sans-serif;"><strong>Make:  </strong><%= @vehicle.make.capitalize %></ons-col>
        </ons-row>
      </ons-list>
      <ons-list>
        <ons-row style=" margin-bottom: 15px;">
          <ons-col width="100%" style="font-size:1.2rem; font-family: 'Raleway', sans-serif;"><strong>Model:  </strong><%= @vehicle.model.capitalize %></ons-col>
        </ons-row>
      </ons-list>
      <ons-list>
        <ons-row style=" margin-bottom: 15px;">
          <ons-col width="100%" style="font-size:1.2rem; font-family: 'Raleway', sans-serif;"><strong>Color:  </strong><%= @vehicle.color.capitalize %></ons-col>
        </ons-row>
      </ons-list>
      <ons-list>
        <ons-row style=" margin-bottom: 15px;">
          <ons-col width="100%" style="font-size:1.2rem; font-family: 'Raleway', sans-serif;"><strong>License Plate:  </strong><%= @vehicle.license_plate %></ons-col>
        </ons-row>
      </ons-list>
      <ons-list>
        <ons-row style=" margin-bottom: 15px;">
          <ons-col width="100%" style="font-size:1.2rem; font-family: 'Raleway', sans-serif;"><strong>VIN#:  </strong><i class="far fa-question-circle" style= font-size:0.8rem;
            onclick="ons.notification.toast('The VIN (vehicle identification number) can often be found on the lower-left corner of the dashboard, in front of the steering wheel. You can read the number by looking through the windshield.', { timeout: 3000})"></i> <%= @vehicle.vin %></ons-col>
        </ons-row>
      </ons-list>
      <ons-list>
        <ons-row style=" margin-bottom: 15px;">
          <ons-col width="100%" style="font-size:1.2rem; font-family: 'Raleway', sans-serif;"><strong>Date of Last Inspection:  </strong>  <%= @vehicle.inspection_date %></ons-col>
        </ons-row>
      </ons-list>
    
    </div>
  </ons-card>

  <div class="actions" style="text-align: center; margin-top: 30px; margin-bottom: 30px;">
      <%= link_to 'Edit Vehicle', edit_vehicle_path, class: "button", style:"background-color: white; color:#3A405A; font-weight: bold;" %>
      <%= link_to 'Add Log', new_vehicle_maintenance_log_path(@vehicle.id), class: "button", style:"background-color: white; color:#3A405A; font-weight: bold;" %>
      <%= link_to 'View Log', vehicle_maintenance_logs_path(@vehicle.id), class: "button", style:"background-color: white; color:#3A405A; font-weight: bold;" %><br>
      <%= link_to 'View Receipts', vehicle_receipts_path(@vehicle.id), class: "button", style:"background-color: white; color:#3A405A; font-weight: bold; margin-top: 15px;" %>
      <%= link_to "", @vehicle, method: :delete, data: { confirm: 'Are you sure?' }, class: "button far fa-trash-alt", style:"margin-top: 15px; background-color: #D1D7E2; color:#3A405A; font-weight: bold; padding: 10px 20px 10px; font-size: 2rem;" %>
  </div>

  <div style="text-align: center;">
  
  </div>

</ons-page>

<i class="far fa-trash-alt"></i>