config/routes.rb
Rails.application.routes.draw do
 
  get 'reminders/oilchange'
  resources :reminders
  get 'notifications/reminder'
  #devise_for :users
  
  get 'welcome/home', to: 'welcome#home'
  #root to: 'welcome#home'
  
  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign me up' }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :maintenance_actions
  
  resources :users
  resources :vehicles do
  resources :maintenance_actions 
  end


  get "maintenance_actions/reminder", to: "maintenance_actions#reminder"
  resources :vehicles do
    get 'reminders/oilchange'
    resources :receipts
    resources :maintenance_logs do
      
      resources :maintenance_actions 
    end
      
  end
     


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end

app/models/alignment.rb
class Alignment < MaintenanceAction

end  
  

app/models/antifreeze.rb
class Antifreeze < MaintenanceAction

end  
  

app/models/brake.rb
class Brake < MaintenanceAction

end
  

app/models/brake_fluid.rb
class BrakeFluid < MaintenanceAction
 
end  

app/models/generate_pdf.rb
class GeneratePdf < Prawn::Document

  include ActionView::Helpers::NumberHelper

  def initialize (maintenance_action)
    super(top_margin: 20)
    @maintenance_actions = maintenance_action.order("service_date")
    line_items
    
    end
  end


  def line_items
    move_down 50
    table line_item_rows do
      row(0).font_style = :bold
      columns(1..3).align = :right
      self.row_colors = ['DDDDDD', 'FFFFFF']
      self.header = true
    end
  end


  def line_item_rows
  
    [["Maintnenace Type", "Service Date", "Mileage", "Cost" ]] +
      @maintenance_actions.map do |maintenance_action|
      [maintenance_action.type, maintenance_action.service_date, maintenance_action.mileage, number_to_currency(maintenance_action.cost)]
      
    end
  end
  

  private

  def generate_pdf
    params.permit(:vehicle_id, :maintenance_log_id, :maintenance_action_id )
  end

  def maintenance_action_params
    params.require(:maintenance_action).permit(:id, :maintenance_log_id, :type, :mileage, :oil_type, :service_date, :cost, :tire_location, :brake_location, :rotor_location, :notes, :selected)
  end
  
  def maintenance_log_params
    params.require(:maintenance_log).permit(:id)
  end
  def vehicle_params
    params.require(:vehicle).permit(:id, :name, :year, :make, :model, :insurance, :vin, :license_plate,
                                    :tire_psi, :registration, :title, :inspection, :color, :user_id, 
                                    :authenticity_token)
 end

  

app/models/maintenance_log.rb
class MaintenanceLog < ApplicationRecord
  
  has_many :maintenance_actions
  belongs_to :vehicle, dependent: :destroy
  accepts_nested_attributes_for :maintenance_actions
  has_one_attached :image
  has_one :converted_receipt
end

app/models/miscellaneous.rb
class Miscellaneous < MaintenanceAction

end  

app/models/oil_change.rb
class OilChange < MaintenanceAction
  

end

app/models/reminder.rb
class Reminder < ApplicationRecord
end

app/models/rotor.rb
class Rotor < MaintenanceAction
end
  

app/models/tire_replacement.rb
class TireReplacement < MaintenanceAction
end  

app/models/tire_rotation.rb
class TireRotation < MaintenanceAction

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :trackable, :validatable

  has_many :vehicles, dependent: :destroy
  has_one_attached :avatar
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

  belongs_to :user
  has_many :maintenance_logs
  has_one_attached :avatar
  #has_one_attached :registration
end

app/controllers/maintenance_actions_controller.rb
class MaintenanceActionsController < ApplicationController
  before_action :authenticate_user!

  def show
    @maintenance_action = MaintenanceAction.find(params[:id])
    @maintenance_log = MaintenanceLog.find_by_id(@maintenance_action.maintenance_log_id)
    @vehicle = Vehicle.find_by_id(@maintenance_log.vehicle_id)
  end  

  # def index
    
  #   @maintenance_actions = MaintenanceAction.all
  #   respond_to do |format|
  #     format.html
  #     format.pdf do
  #       pdf = GeneratePdf.new(@maintenance_actions)
  #       send_data pdf.render, 
  #                 filename: "Export",
  #                 type: 'application/pdf',
  #                 disposition: 'inline'
       
  #     end
  #   end
  # end
 
  def new 
    @maintenance_action = Maintenance_action.new 
  end

  def edit
    @maintenance_action = MaintenanceAction.find(params[:id])  
  
  end
  
  def update
    @maintenance_action = MaintenanceAction.find(params[:id])

    if @maintenance_action.update(maintenance_action_params)
        redirect_to maintenance_action_path
    else
        render 'edit'
    end
  end

  def create 
    @maintenance_action
  end 

  def destroy 

  end
  
  private 
  def maintenance_action_params
    params.require(:maintenance_action).permit(:maintenance_log_id, :type, :mileage, :oil_type, :service_date, :cost, :tire_location, :brake_location, :rotor_location, :notes, :selected)
  end

end

app/helpers/maintenance_actions_helper.rb
module MaintenanceActionsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/maintenance_actions/_form.html.erb
<%= form_for(@maintenance_action, local: true) do |f| %>

  <% case @maintenance_action.type%>
    <% when "OilChange"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Oil Change</h2>
          <div>
              <%= f.label :service_date , style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date , style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea",  onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :oil_type, style: "margin-left: 10px;"   %>
              <%= f.select :oil_type, options_for_select([ "Regular", "Synthetic" ], "Regular"), style: "padding-left: 25px;" %>
          </div><br>
            <div>
              <%= f.label :cost, style: "margin-left: 10px; margin-top: 10px;"   %><br>
              <%= f.text_field :cost, class: "textarea", onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :oilchange_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>

          </div>
    
                  
    <% when "Brake"%>
       <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Brakes</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea",  onblur:"validate(this)",style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :brake_location, style: "margin-left: 10px;"  %>
              <%= f.select :brake_location, options_for_select([ "Front", "Rear", "All" ], "All"), class:"select-input select-input--material" %>
          </div><br>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"   %><br>
              <%= f.text_field :cost, class: "textarea", onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :brake_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>

          </div>
      
  </div>
    <% when "Rotor"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Rotors</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea",onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :rotor_location, style: "margin-left: 10px;"  %>
              <%= f.select :rotor_location, options_for_select([ "Front", "Rear", "All" ], "All") %>
          </div><br>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea",  onblur:"validate(this)",style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :rotor_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>

          </div>
      
  </div>
<% when "TireReplacement"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Tire Replacement</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"   %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea", onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;"  %>
          </div>
          <div>
              <%= f.label :tire_location, style: "margin-left: 10px;"   %>
              <%= f.select :tire_location, options_for_select([ "Front-Left", "Front-Right", "Back-Left", "Back-Right","Front-2", "Back-2", "All" ], "All") %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :tire_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>

          </div>
      
  </div>
<% when "TireRotation"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Tire Rotations</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :tire_rotation_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>

          </div>
      
  </div>
<% when "Alignment"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Alignments</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea", onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :alignment_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>

          </div>
      
  </div>
<% when "Antifreeze"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Anti Freeze</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea",  onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea",  onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :antifreeze_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>

          </div>
      
  </div>
<% when "BrakeFluid"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Brake Fluids</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea",  onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :brake_fluid_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>
          </div>
      
  </div>
<% when "PowerSteeringFluid"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Power Steering Fluid</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea",  onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :powersteering_fluid_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>
          </div>
      
  </div>
<% when "TransmissionFluid"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Transmission Fluid</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea",  onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :transmission_fluid_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>
          </div>
      
  </div>
<% when "Miscellaneous"%>
      <h2 style="text-align: center; margin-top: 30px; font-family: 'Raleway', sans-serif;">Miscellaneous</h2>
          <div>
              <%= f.label :service_date, style: "margin-left: 10px; margin-bottom: 10px;"  %><br>
              <%= f.date_field :service_date, style: "margin-left: 10px; margin-bottom: 10px; margin-top: 10px;" %>
          </div>
          <div>
              <%= f.label :mileage, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :mileage, class: "textarea",  onblur:"validate(this)", style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
            <div>
              <%= f.label :cost, style: "margin-left: 10px;"  %><br>
              <%= f.text_field :cost, class: "textarea", onblur:"validate(this)",  style: "margin-bottom: 5px; margin-left: 10px;" %>
          </div>
          <div>
              <%= f.label :miscellaneous_notes, style: "margin-left: 10px;"  %><br>
              <%= f.text_area :notes, class:"textarea", style: "margin-bottom: 5px; margin-left: 10px; margin-top: 10px;"%>
          </div>
    
  </div>      
      

  <%end%>
  <div class="actions" style="text-align: center; margin-top: 30px; margin-bottom: 30px;">
      <%= f.submit "Submit" => new_maintenance_action_path, class: "button", style:"background-color: white; color:#3A405A; font-weight: bold;" %>
    </div>
<%end%>

app/views/maintenance_actions/edit.html.erb
<ons-page>
  <ons-toolbar style="background-color: #3A405A;">
    <div class="left">
      <ons-toolbar-button><%= link_to 'Back', :back , class:"button--quiet", style:"color: white;" %></ons-toolbar-button>
    </div>
    <div class="center"><%= link_to 'GloveBox', vehicles_path, class:"button--quiet", style:"color: white; font-weight:bold;"  %></div>
  </ons-toolbar>
 
<h2 style="text-align: center; margin-top: 10px; font-family: 'Raleway', sans-serif;">Edit Maintenance Action</h2>


<%= render 'form' %>

app/views/maintenance_actions/index.html.erb
<h2>Maintenance History</h2>

<% @maintenance_logs.each do |maintenance_log| %>
   <% maintenance_log.maintenance_actions.each do |maintenance_action| %>
  

  <%case maintenance_action.type%>
  <% when "OilChange"%>
  <div>
  <ul>
      <li> Maintenance Type - <%= maintenance_action.type %></li>
      <li> Service Date - <%= maintenance_action.service_date %></td></li>
      <li> Mileage At Time Of Service - <%= maintenance_action.mileage %></li>
      <li> Cost - <%= maintenance_action.cost %></li>
      <li> Oil Type - <%= maintenance_action.oil_type %></li>
      <li> Notes - <%= maintenance_action.notes %></li>
  </ul>
  </thead>
  </div>
    <div>
    <tbody>
      <tr>
      <td><%= maintenance_action.type %></td>
        <td><%= maintenance_action.service_date %></td>
        <td><%= maintenance_action.mileage %></td>
        <td><%= maintenance_action.cost %></td>
        <td><%= maintenance_action.oil_type %></td>
        <td><%= maintenance_action.notes %></td>
      </tr>
    <tbody>
    </div>
    
    <% when "Brake"%>
    <div>
    <thead>
    <tr>
      <th> Maintenance Type</th>
      <th> Service Date</th>
      <th> Mileage At Time Of Service</th>
      <th> Cost</th>
      <th> Brake Location</th>
      <th> Notes</th>
    </tr>
  </thead>
    </div>

    <div>
    <tbody>
      <tr>
      <td><%= maintenance_action.type %></td>
        <td><%= maintenance_action.service_date %></td>
        <td><%= maintenance_action.mileage %></td>
        <td><%= maintenance_action.cost %></td>
        <td><%= maintenance_action.brake_location %></td>
        <td><%= maintenance_action.notes %></td>
      </tr>
    <tbody>
    </div>

    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.brake_location %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "Rotor"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>  
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.rotor_location %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "TireRotation"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.tire_location %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "TireReplacement"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>  
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.tire_location %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "Alignment"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "PowerSteeringFluid"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>  
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "Antifreeze"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "TransmissionFluid"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>  
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "BrakeFluid"%>
    <div>
      <p>
        <strong></strong>
        <%= maintenance_action.type %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.service_date %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.mileage %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.cost %>
      </p>
      <p>
        <strong></strong>
        <%= maintenance_action.notes %>
      </p>
    </div>
    <% when "Miscellaneous"%>
    <div>
    <p>
      <strong></strong>
      <%= maintenance_action.type %>
    </p>
    <p>
      <strong></strong>
      <%= maintenance_action.service_date %>
    </p>
    <p>
      <strong></strong>
      <%= maintenance_action.mileage %>
    </p>
    <p>
      <strong></strong>
      <%= maintenance_action.cost %>
    </p>
    <p>
      <strong></strong>
      <%= maintenance_action.notes %>
    </p>
  </div>

    <%end%>
    <%end%>
  <%end%>